site_name: Consolidated Storage on Nutanix
site_url: https://github.com/nutanix-japan/Consolidated_Storage_Bootcamp_Material
site_author: Lakshmi Balaramane

# Repository

repo_name: nutanix-japan/Consolidated_Storage_Bootcamp_Material
repo_url: https://github.com/nutanix-japan/Consolidated_Storage_Bootcamp_Material

# Copyright
copyright: Copyright &copy; 2016 - 2022 Nutanix APAC Enablement Practice

# Configuration

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.footer
  # - navigation.sections # leave this commented for sections
  # - navigation.expand
  - navigation.top
  - navigation.integrate
  - search.highlight
  - search.suggest
  - toc.follow
  - content.code.copy
  palette:

    #Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
    - search

nav:
    - Home: index.md
    - Files:
      - 'SMB Share': files_smb_share/files_smb_share.md
      - 'NFS Share': files_nfs_export/files_nfs_export.md
      - 'Blocking': files_file_blocking/files_file_blocking.md
      - 'Multiprotocol': files_multiprotocol/files_multiprotocol.md
      - 'Replication': files_replication/files_replication.md
    - Objects:
      - 'Buckets & UAC': objects_buckets_users_access_control/objects_buckets_users_access_control.md
      - 'Versioning':  objects_versioning_access_control/objects_versioning_access_control
      - 'Access from CLI and Scripts': objects_cli_scripts/objects_cli_scripts.md
      - 'Tiering': objects_tiering/objects_tiering.md
      - 'Multiprotocol': objects_multiprotocol/objects_multiprotocol.md
      - 'Multi-cluster': objects_multi_cluster/objects_multi_cluster.md
    - 'Optional Labs':
      - 'Deploy Nutanix Files': files_deploy/files_deploy.md
      - 'Expand Files Cluster': files_expand_cluster/files_expand_cluster.md

